version: "3.4"

# Ubuntu , set this for redpanda to start
# https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_ubuntu/ch04s03.htm

# Clickhouse Table Schema
# create table test(id int, message String) ENGINE=MergeTree() PRIMARY KEY id;

services:
  mysql-master:
    extends:
      file: mysql-master-service.yml
      service: mysql-master

  mysql-slave:
    extends:
      file: mysql-slave-service.yml
      service: mysql-slave
    depends_on:
      - mysql-master

  clickhouse:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    extends:
      file: zookeeper-service.yml
      service: zookeeper

  clickhouse-sink-connector-lt:
    extends:
      file: clickhouse-sink-connector-lt-service.yml
      service: clickhouse-sink-connector-lt

  ### MONITORING ####
  prometheus:
    extends:
      file: prometheus-service.yml
      service: prometheus

  grafana:
    extends:
      file: grafana-service.yml
      service: grafana
    volumes:
      - ./config/grafana/config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/config/altinity_sink_connector.json:/var/lib/grafana/dashboards/altinity_sink_connector.json
    depends_on:
      - prometheus

  jmx_exporter:
    container_name: jmx_exporter
    image: sscaling/jmx-prometheus-exporter
    restart: "no"
    ports:
      - "9072:9072"
    environment:
      SERVICE_PORT: 9072
    volumes:
      - ./config/jmx-config.yml:/opt/jmx_exporter/config.yml
    ## END OF MONITORING ###
