version: "3.4"

services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim
    restart: always
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=dbz
      - ORACLE_USER=debezium
      - ORACLE_DATABASE=ORCLCDB
      - ORACLE_PASSWORD=dbz
      - ORACLE_PDB=ORCLPDB1
    volumes:
      - ../sql/init_oracle.sql:/docker-entrypoint-initdb.d/init_oracle.sql
    # No need for a command override; the image entrypoint is sufficient
