version: "3.4"

services:
  postgres:
    image: debezium/postgres:15-alpine
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U root -d public' ]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=public
    volumes:
      - ../sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
