version: "3.4"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.9.1
    restart: "no"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
