apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  namespace: redpanda
  name: redpanda
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
      - external:
          enabled: true
    pandaproxyApi:
      - port: 8082
      - external:
          enabled: true
    adminApi:
      - port: 9644
    developerMode: false
