{
 "title": "Altinity Sink Connector for ClickHouse",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select seconds_behind_source from altinity_sink_connector.show_replica_status",
     "rawQuery": "select seconds_behind_source from altinity_sink_connector.show_replica_status",
     "round": "0s"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Altinity Sink Connector for ClickHouse",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "options": {
    "content": "<div>\n  <img width=\"100\" height=\"100\" src=\"https://logosandtypes.com/wp-content/uploads/2020/12/altinity.svg\"/>\n<p>Altinity Sink Connector for ClickHouse</p>\n<p>For more information, visit <href https://github.com/Altinity/clickhouse-sink-connector\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bin Log file/position",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clickhouse_sink_binlog_pos{}", "legendFormat": "{{file}}" }
   ]
  },
  {
   "title": "GTID - Transaction Id",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clickhouse_sink_gtid{}" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clickhouse_sink_topics_error_records_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UpTime(secs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clickhouse_sink_connector_uptime/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records (Topic)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(clickhouse_sink_topics_num_records_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Debezium -> CH Lag (secs)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "clickhouse_sink_debezium_lag/1000"
    }
   ]
  },
  {
   "title": "Rate(Total Records)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(clickhouse_sink_topics_num_records_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Source DB -> CH Lag (secs)",
   "type": "barchart",
   "description": "Lag calculated from time records are inserted to CH and the timestamp recorded by debezium connector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "clickhouse_sink_db_lag/1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DDL Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "clickhouse_sink_ddl_total{}", "legendFormat": "{{ddl}}" }
   ]
  },
  {
   "title": "Rows inserted ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT  toStartOfInterval(event_time, toIntervalSecond(1)) AS _time_dec,\nsum(rows) as rows, table\nFROM system.part_log\nWHERE (event_type = 'NewPart') AND event_time >= toDateTime($from) and  event_time < toDateTime($to)\nGROUP BY _time_dec, table\nORDER BY _time_dec",
     "rawQuery": "SELECT  toStartOfInterval(event_time, toIntervalSecond(1)) AS _time_dec,\nsum(rows) as rows, table\nFROM system.part_log\nWHERE (event_type = 'NewPart') AND event_time >= toDateTime(1681314113) and  event_time < toDateTime(1681335713)\nGROUP BY _time_dec, table\nORDER BY _time_dec",
     "round": "0s"
    }
   ]
  },
  { "title": "Processor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 39 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage(Process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 39 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "Contains the system load average (the number of items waiting in the CPU run-queue) information for each machine in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "__auto" }
   ]
  },
  { "title": "JVM Stats (Memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory Used(MB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Max (MB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "jvm_memory_max_bytes/1000000" }
   ]
  },
  { "title": "JVM Stats (Garbage Collector)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Size of long-lived heap memory pool (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max size of long-lived heap memory pool (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Stats (Threads)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Current number of live threads ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Live Thread States",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}