{{- if .Values.postgres -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-connector-lightweight-config
data:
  config.yml: |-
    name: "debezium-embedded-postgres"
    auto.create.tables.replicated: "true"
    database.hostname: "postgres"
    database.port: "5432"
    database.user: "root"
    database.password: "root"
    database.server.name: "ER54"
    schema.include.list: public,public2
    slot.name: connector2
    plugin.name: "pgoutput"
    #table.include.list: "public.tm,public.tm2"
    clickhouse.server.url: "clickhouse"
    clickhouse.server.user: "root"
    clickhouse.server.password: "root"
    clickhouse.server.port: "8123"
    database.allowPublicKeyRetrieval: "true"
    snapshot.mode: "initial"
    offset.flush.interval.ms: 5000
    connector.class: "io.debezium.connector.postgresql.PostgresConnector"
    offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
    offset.storage.jdbc.table.name: "altinity_sink_connector.replica_source_info"
    offset.storage.jdbc.url: "jdbc:clickhouse://clickhouse:8123/altinity_sink_connector"
    offset.storage.jdbc.user: "root"
    offset.storage.jdbc.password: "root"
    offset.storage.jdbc.table.ddl: "CREATE TABLE if not exists %s
    (
      `id` String,
      `offset_key` String,
      `offset_val` String,
      `record_insert_ts` DateTime,
      `record_insert_seq` UInt64,
      `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
    )
    ENGINE = ReplacingMergeTree(_version)
    ORDER BY id
    SETTINGS index_granularity = 8192"
    offset.storage.jdbc.table.delete: "select * from %s"
    enable.snapshot.ddl: "true"
    auto.create.tables: "true"
    database.dbname: "public"
    clickhouse.jdbc.params: "keepalive.timeout=3,max_buffer_size=1000000,socket_timeout=30000,connection_timeout=30000"
    metrics.enable: "true"
    replica.status.view: "CREATE OR REPLACE VIEW altinity_sink_connector.show_replica_status
    (
      `seconds_behind_source` Int32,
      `duration_behind_source` String,
      `utc_time` DateTime('UTC'),
      `local_time` DateTime,
      `id` String,
      `offset_key` String,
      `offset_val` String,
      `record_insert_ts` DateTime,
      `record_insert_seq` UInt64
    ) AS
    SELECT *
    FROM
    (
      SELECT
        now() - fromUnixTimestamp(JSONExtractUInt(offset_val, 'ts_sec')) AS seconds_behind_source,
        formatReadableTimeDelta(seconds_behind_source) AS duration_behind_source,
        toDateTime(fromUnixTimestamp(JSONExtractUInt(offset_val, 'ts_sec')), 'UTC') AS utc_time,
        fromUnixTimestamp(JSONExtractUInt(offset_val, 'ts_sec')) AS local_time,
        *
      FROM merge(altinity_sink_connector, 'replica_source_info_.*')
      FINAL
    ) AS U
    ORDER BY offset_key ASC"
    use.nongraceful.disconnect: "true"
    database.keep.alive.interval.ms: "30000"
    database.connection.reconnect.backoff.ms: "1000"
    database.connection.reconnect.backoff.max.ms: "10000"
    database.ssl.mode: "disabled"
{{- else -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-connector-lightweight-config
data:
    config.yml: |-
      name: "company-1"
      topic.prefix: "sink-connector-1"
      database.hostname: "mysql-master"
      database.port: "3306"
      database.user: "root"
      database.password: "root"
      database.server.id: "12345"
      database.server.name: "ER54"
      database.include.list: sbtest
      #table.include.list: ""
      clickhouse.server.url: "clickhouse"
      clickhouse.server.user: "root"
      clickhouse.server.password: "root"
      clickhouse.server.port: "8123"
      database.allowPublicKeyRetrieval: "true"
      snapshot.mode: "initial"
      offset.flush.interval.ms: 5000
      connector.class: "io.debezium.connector.mysql.MySqlConnector"
      offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
      offset.storage.jdbc.table.name: "altinity_sink_connector.replica_source_info"
      offset.storage.jdbc.url: "jdbc:clickhouse://clickhouse:8123/altinity_sink_connector"
      offset.storage.jdbc.user: "root"
      offset.storage.jdbc.password: "root"
      offset.storage.jdbc.table.ddl: "CREATE TABLE if not exists %s
      (
        `id` String,
        `offset_key` String,
        `offset_val` String,
        `record_insert_ts` DateTime,
        `record_insert_seq` UInt64,
        `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
      )
      ENGINE = ReplacingMergeTree(_version)
      ORDER BY id
      SETTINGS index_granularity = 8192"
      offset.storage.jdbc.table.delete: "select * from %s"
      offset.storage.jdbc.table.select: "SELECT id, offset_key, offset_val FROM %s FINAL ORDER BY record_insert_ts, record_insert_seq"
      schema.history.internal: "io.debezium.storage.jdbc.history.JdbcSchemaHistory"
      schema.history.internal.jdbc.url: "jdbc:clickhouse://clickhouse:8123/altinity_sink_connector"
      schema.history.internal.jdbc.user: "root"
      schema.history.internal.jdbc.password: "root"
      schema.history.internal.jdbc.table.ddl: "CREATE TABLE if not exists %s
      (`id` VARCHAR(36) NOT NULL, `history_data` VARCHAR(65000), `history_data_seq` INTEGER, `record_insert_ts` TIMESTAMP NOT NULL, `record_insert_seq` INTEGER NOT NULL) ENGINE=ReplacingMergeTree(record_insert_seq) order by id"
      schema.history.internal.jdbc.schema.history.table.name: "altinity_sink_connector.replicate_schema_history"
      enable.snapshot.ddl: "true"
      persist.raw.bytes: "false"
      auto.create.tables: "true"
      database.connectionTimeZone: "America/Chicago"
      errors.max.retries: 20
      clickhouse.datetime.timezone: "America/Chicago"
      ignore.ddl.regex: "(?i)(ANALYZE PARTITION).*"
      clickhouse.jdbc.params: "keepalive.timeout=3,max_buffer_size=1000000,socket_timeout=30000,connection_timeout=30000"
      clickhouse.jdbc.settings: "input_format_null_as_default=0,allow_experimental_object_type=1,insert_allow_materialized_columns=1"
      metrics.enable: "true"
      connection.pool.disable: "true"
      use.nongraceful.disconnect: "true"
      database.keep.alive.interval.ms: "30000"
      database.connection.reconnect.backoff.ms: "1000"
      database.connection.reconnect.backoff.max.ms: "10000"
      database.ssl.mode: "disabled"
      non.default.value: "true"
      single.threaded: "true"
{{- end -}}