apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sink-connector-lightweight.fullname" . }}
  labels:
    {{- include "sink-connector-lightweight.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sink-connector-lightweight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sink-connector-lightweight.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim-sink-connector-lightweight
        - name: config-yml
          configMap:
            name: sink-connector-lightweight-config
            items:
              - key: config.yml
                path: config.yml
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.env }}
              - name: {{ .name }}
                value: {{ .value  | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe: null
          readinessProbe: null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-yml
              mountPath: /config.yml
              subPath: config.yml
            - mountPath: {{ .Values.debezium.pod.mountPath }}
              name: task-pv-storage
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
