apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-sink-connector-lightweight
spec:
  storageClassName: {{ include "sink-connector-lightweight.storageAccountClass" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi