apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-sink-connector-lightweight
  labels: {{ include "sink-connector-lightweight.storageAccountLabel" . }}
spec:
  storageClassName: {{ include "sink-connector-lightweight.storageAccountClass" . }}
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  {{ include "sink-connector-lightweight.hostpathing" . | nindent 2 }}