global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'sink'
    static_configs:
      - targets:
          - clickhouse-sink-connector-lt:8083
  - job_name: 'jmx'
    static_configs:
      - targets:
          - jmx_exporter:9072