FROM quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

LABEL maintainer="Altinity"

USER root:root

# Copy sink-connector
COPY target/*.jar  /opt/kafka/plugins/clickhouse-sink-connector/280d4c6e/

# Copy libs
COPY deploy/libs/* /opt/kafka/plugins/clickhouse-sink-connector/2824cdcf/

# Copy apicurio
RUN 'mkdir' '-p' '/opt/kafka/plugins/clickhouse-sink-connector/3542976d' \
      && 'curl' '-L' '--output' '/opt/kafka/plugins/clickhouse-sink-connector/3542976d.tgz' 'https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/2.1.5.Final/apicurio-registry-distro-connect-converter-2.1.5.Final.tar.gz' \
      && 'tar' 'xvfz' '/opt/kafka/plugins/clickhouse-sink-connector/3542976d.tgz' '-C' '/opt/kafka/plugins/clickhouse-sink-connector/3542976d' \
      && 'rm' '-vf' '/opt/kafka/plugins/clickhouse-sink-connector/3542976d.tgz'

USER 1001
