FROM quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

LABEL maintainer="Altinity"

USER root:root

ADD https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.9.2.Final/debezium-connector-mysql-1.9.2.Final-plugin.tar.gz /opt/kafka/plugins/debezium/
RUN chmod 666 /opt/kafka/plugins/debezium/*

ADD deploy/apicurio-registry-distro-connect-converter/*.jar /opt/kafka/libs/

USER 1001
