"""Sysbench-driven checksum integration test for the sink-connector-lightweight.

Identical in spirit to ``test_checksum_replication.py`` -- it runs the project's
table checksum scripts against MySQL and ClickHouse and asserts every verified
table has an identical (md5, row-count) checksum -- but the data is generated by
the ``severalnines/sysbench`` Docker image instead of ``init_mysql.sql``.

The ``sysbench_stack`` fixture (in conftest.py) prepares sbtest1..N in the
``test`` database before the connector starts, so they are captured by the
initial snapshot and replicated to ClickHouse.
"""

import logging

from conftest import (
    CLICKHOUSE_HOST,
    CLICKHOUSE_PASSWORD,
    CLICKHOUSE_USER,
    DATABASE,
    MYSQL_HOST,
    MYSQL_PASSWORD,
    MYSQL_USER,
    SYSBENCH_TABLES as TABLES,
)

# Reuse the checksum invocation/parsing helpers from the primary checksum test.
from test_checksum_replication import (
    MAX_DATETIME,
    MIN_DATETIME,
    _run_checksum,
)

logger = logging.getLogger(__name__)

TABLES_REGEX = "^(" + "|".join(TABLES) + ")$"


def _mysql_checksums():
    cmd = [
        "python3",
        "db_compare/mysql_table_checksum.py",
        "--mysql_host", MYSQL_HOST,
        "--mysql_user", MYSQL_USER,
        "--mysql_password", MYSQL_PASSWORD,
        "--mysql_database", DATABASE,
        "--tables_regex", TABLES_REGEX,
        "--min_date_value", "1900-01-01",
        "--min_datetime_value", MIN_DATETIME,
        "--max_datetime_value", MAX_DATETIME,
        "--binary_encoding", "base64",
    ]
    return _run_checksum(cmd)


def _clickhouse_checksums():
    cmd = [
        "python3",
        "db_compare/clickhouse_table_checksum.py",
        "--clickhouse_host", CLICKHOUSE_HOST,
        "--clickhouse_user", CLICKHOUSE_USER,
        "--clickhouse_password", CLICKHOUSE_PASSWORD,
        "--clickhouse_database", DATABASE,
        "--tables_regex", TABLES_REGEX,
        "--min_datetime_value", MIN_DATETIME,
        "--max_datetime_value", MAX_DATETIME,
        "--sign_column", "",
        "--exclude_columns", "_version,is_deleted,_is_deleted,__is_deleted,_sign",
    ]
    return _run_checksum(cmd)


def _print_checksums(mysql_results, clickhouse_results):
    """Print (and log) the MySQL vs ClickHouse checksum + row count per table.

    Uses print() so the values are visible in pytest output (captured stdout is
    shown on failure and always with `-s`); logger.info is swallowed by pytest's
    default log capture.
    """
    header = f"{'table':<16} {'mysql_count':>12} {'ch_count':>12}  {'mysql_md5':<34} {'clickhouse_md5':<34}"
    lines = ["", "=== sysbench MySQL -> ClickHouse checksums ===", header, "-" * len(header)]
    for table in TABLES:
        m = mysql_results.get(table)
        c = clickhouse_results.get(table)
        m_md5, m_cnt = (m if m else ("<missing>", "-"))
        c_md5, c_cnt = (c if c else ("<missing>", "-"))
        lines.append(
            f"{table:<16} {str(m_cnt):>12} {str(c_cnt):>12}  {str(m_md5):<34} {str(c_md5):<34}"
        )
    report = "\n".join(lines)
    print(report)
    logger.info(report)


def test_sysbench_checksum_matches(sysbench_stack):
    mysql_results = _mysql_checksums()
    clickhouse_results = _clickhouse_checksums()

    _print_checksums(mysql_results, clickhouse_results)

    mismatches = []
    for table in TABLES:
        mysql_val = mysql_results.get(table)
        ch_val = clickhouse_results.get(table)
        if mysql_val is None:
            mismatches.append(f"{table}: missing MySQL checksum")
        elif ch_val is None:
            mismatches.append(f"{table}: missing ClickHouse checksum")
        elif mysql_val != ch_val:
            mismatches.append(
                f"{table}: mysql(md5={mysql_val[0]}, count={mysql_val[1]}) != "
                f"clickhouse(md5={ch_val[0]}, count={ch_val[1]})"
            )

    assert not mismatches, "MySQL -> ClickHouse checksum mismatch:\n" + "\n".join(mismatches)
