{
 "title": "ClickHouse_Sink_Connector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Source Lag(Min)",
   "type": "timeseries",
   "description": "Lag between MySQL insert and ClickHouse insert time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clickhouse_source_lag_min_total{instance=\"sink:8084\",job=\"sink\"}/1000"
    }
   ]
  },
  {
   "title": "Consumer Lag(Min)",
   "type": "timeseries",
   "description": "Lag between time message written to Kafka broker and the time it was persisted to CH.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "clickhouse_consumer_lag_min_total{instance=\"sink:8084\",job=\"sink\"}/1000"
    }
   ]
  },
  {
   "title": "Source Lag(Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "clickhouse_source_lag_max_total{instance=\"sink:8084\",job=\"sink\"}/1000"
    }
   ]
  },
  {
   "title": "Consumer Lag(Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "clickhouse_consumer_lag_max_total{instance=\"sink:8084\",job=\"sink\"}/1000"
    }
   ]
  },
  {
   "title": "Block Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{table=\"products\"}"
    }
   ]
  }
 ]
}