apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --file clickhouse-sink-connector-lt-service.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: clickhouse-sink-connector-lt
  name: clickhouse-sink-connector-lt
spec:
  containers:
    - command:
        - sh
        - -c
        - java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms4g -Xmx4g -Dlog4j2.configurationFile=log4j2.xml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=39999 -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication
      image: altinity/clickhouse-sink-connector:2.5.1-lt
      name: clickhouse-sink-connector-lt
      ports:
        - containerPort: 8083
          protocol: TCP
        - containerPort: 5005
          protocol: TCP
        - containerPort: 7000
          protocol: TCP
        - containerPort: 39999
          protocol: TCP
      volumeMounts:
        - mountPath: /log4j2.xml
          name: clickhouse-sink-connector-lt-cm0
          subPath: log4j2.xml
        - mountPath: /config.yml
          name: clickhouse-sink-connector-lt-cm1
          subPath: config.yml
  restartPolicy: Never
  volumes:
    - configMap:
        items:
          - key: log4j2.xml
            path: log4j2.xml
        name: clickhouse-sink-connector-lt-cm0
      name: clickhouse-sink-connector-lt-cm0
    - configMap:
        items:
          - key: config.yml
            path: config.yml
        name: clickhouse-sink-connector-lt-cm1
      name: clickhouse-sink-connector-lt-cm1
