{
 "title": "altinity_sink_connector_clickhouse",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Altinity Sink Connector for ClickHouse",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <img width=\"100\" height=\"100\" src=\"https://logosandtypes.com/wp-content/uploads/2020/12/altinity.svg\"/>\n<p>Altinity Sink Connector for ClickHouse</p>\n<p>For more information, visit <href https://github.com/Altinity/clickhouse-sink-connector\n</div>"
   }
  },
  {
   "title": "Bin Log position",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clickhouse_sink_binlog_pos{}" }
   ]
  },
  {
   "title": "GTID - Transaction Id",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clickhouse_sink_gtid{}" }
   ]
  },
  {
   "title": "Records (Topic)",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "clickhouse_topics_num_records_total{}"
    }
   ]
  }
 ]
}