FROM quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

LABEL maintainer="Altinity"

USER root:root

RUN 'mkdir' '-p' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744' \
      && 'curl' '-L' '--output' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744.tgz' 'https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/1.9.2.Final/debezium-connector-mysql-1.9.2.Final-plugin.tar.gz' \
      && 'tar' 'xvfz' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744.tgz' '-C' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744' \
      && 'rm' '-vf' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744.tgz'

#RUN 'mkdir' '-p' '/opt/kafka/plugins/debezium-mysql-connector/3542976d' \
#      && 'curl' '-L' '--output' '/opt/kafka/plugins/debezium-mysql-connector/3542976d.tgz' 'https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/2.1.5.Final/apicurio-registry-distro-connect-converter-2.1.5.Final.tar.gz' \
#      && 'tar' 'xvfz' '/opt/kafka/plugins/debezium-mysql-connector/3542976d.tgz' '-C' '/opt/kafka/plugins/debezium-mysql-connector/3542976d' \
#      && 'rm' '-vf' '/opt/kafka/plugins/debezium-mysql-connector/3542976d.tgz'


# old version -> 3.1.0
# Copy confluent
RUN 'curl' '-L' '--output' '/opt/kafka/libs/kafka-connect-avro-converter-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/5.3.0/kafka-connect-avro-converter-5.3.0.jar'
RUN 'curl' '-L' '--output' '/opt/kafka/libs/kafka-avro-serializer-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar'
RUN 'curl' '-L' '--output' '/opt/kafka/libs/kafka-schema-registry-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-schema-registry/5.3.0/kafka-schema-registry-5.3.0.jar'


RUN 'curl' '-L' '--output' '/opt/kafka/libs/kafka-schema-registry-client-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar'
RUN 'curl' '-L' '--output' '/opt/kafka/libs/common-config-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/common-config/5.3.0/common-config-5.3.0.jar'
RUN 'curl' '-L' '--output' '/opt/kafka/libs/common-utils-5.3.0.jar' 'https://packages.confluent.io/maven/io/confluent/common-utils/5.3.0/common-utils-5.3.0.jar'

RUN 'curl' '-L' '--output' '/opt/kafka/libs/avro-1.10.1.jar' 'https://repo1.maven.org/maven2/org/apache/avro/avro/1.10.1/avro-1.10.1.jar'


RUN 'curl' '-L' '--output' '/opt/kafka/libs/jackson-mapper-asl-1.9.13.jar' 'https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar'
RUN 'curl' '-L' '--output' '/opt/kafka/plugins/debezium-mysql-connector/c2d5b744/debezium-connector-mysql/jackson-mapper-asl-1.9.13.jar' 'https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar'


#RUN 'curl' '-L' '--output' '/opt/kafka/plugins/debezium-mysql-connector/3542976d/kafka-serde-tools-package-3.1.0-tests.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-serde-tools-package/3.1.0/kafka-serde-tools-package-3.1.0-tests.jar'


#USER 1001
