name: Pull Request Pipeline

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - '**'

jobs:
  build-kafka-lightweight:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      IMAGE_TAG: ${{ github.event.number }}-${{ github.sha }}

#  testflows-kafka:
#    needs: [build-kafka-lightweight]
#    uses: ./.github/workflows/testflows-sink-connector-kafka.yml
#    secrets: inherit
#    with:
#      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-kafka
  testflows-lightweight-x86:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/testflows-sink-connector-lightweight.yml
    secrets: inherit
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt
      extra_args: ""
      artifact_suffix: ""

  testflows-lightweight-x86-hikari-pool:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/testflows-sink-connector-lightweight.yml
    secrets: inherit
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt
      extra_args: --hikari-pool
      artifact_suffix: hikari-pool

  # testflows-lightweight-arm:
  #   needs: [build-kafka-lightweight]
  #   uses: ./.github/workflows/testflows-sink-connector-lightweight-arm.yml
  #   secrets: inherit
  #   with:
  #     SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt
  #     extra_args: ""
  #     artifact_suffix: ""

  # testflows-lightweight-arm-hikari-pool:
  #   needs: [build-kafka-lightweight]
  #   uses: ./.github/workflows/testflows-sink-connector-lightweight-arm.yml
  #   secrets: inherit
  #   with:
  #     SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt
  #     extra_args: --hikari-pool
  #     artifact_suffix: hikari-pool

  java-tests-kafka:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-kafka-tests.yml
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-kafka

  java-tests-lightweight:
    needs: [build-kafka-lightweight]
    uses: ./.github/workflows/sink-connector-lightweight-tests.yml
    with:
      SINK_CONNECTOR_IMAGE: altinityinfra/clickhouse-sink-connector:${{ github.event.number }}-${{ github.sha }}-lt

  publish-lightweight-jar:
    needs: [build-kafka-lightweight]
    runs-on: ubuntu-latest
    steps:
      - name: Download Lightweight jar artifact
        uses: actions/download-artifact@v4
        with:
          name: clickhouse-sink-connector-lt-${{ github.event.number }}-${{ github.sha }}.jar
          path: ./artifacts

      - name: Upload Lightweight jar
        uses: actions/upload-artifact@v4
        with:
          name: clickhouse-sink-connector-lt.jar
          path: ./artifacts/*.jar
